# Generated by Django 6.0.3 on 2026-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_client_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
